In [1]:
# Libraries

import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

# Question 1

In [2]:
np.__version__

'1.21.5'

# Getting the data

In [10]:
df = pd.read_csv("/Users/admin/Documents/Data Science/ml-zoomcamp/data.csv")

In [11]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

# Question 2

In [13]:
# How many records are in the dataset?
df.shape

(11914, 16)

11,914 records

# Question 3


In [15]:
# Who are the most popular car manufacturers (top-3) according to the dataset?

df["Make"].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

Top three (3) cars are Chevrolet, Ford, Volkswagen

# Question 4


In [21]:
# What's the number of unique Audi car models in the dataset?
(df[df["Make"] == "Audi"]).shape[0]

328

# Question 5

In [23]:
# How many columns in the dataset have missing values?

df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

five (5) columns have missing values

# Question 6

Find the median value of "Engine Cylinders" column in the dataset.
Next, calculate the most frequent value of the same "Engine Cylinders".
Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
Now, calculate the median value of "Engine Cylinders" once again.
Has it changed?

Hint: refer to existing mode and median functions to complete the task.

Yes
No


In [25]:
# Find the median value of "Engine Cylinders" column in the dataset
df["Engine Cylinders"].median()

6.0

In [32]:
# The most frequent value of the same "Engine Cylinders"
most_freq_value = df["Engine Cylinders"].mode()
most_freq_value

0    4.0
Name: Engine Cylinders, dtype: float64

In [34]:
#Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step
df["Engine Cylinders"].fillna(4, inplace=True)

In [35]:
df["Engine Cylinders"].median()

6.0

No. The median value has not changed.

# Question 7
Select all the "Lotus" cars from the dataset.
Select only columns "Engine HP", "Engine Cylinders".
Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the first element of w?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

-0.0723
4.5949
31.6537
63.5643

In [40]:
# Select all the "Lotus" cars from the dataset
lotus_cars = df[df["Make"] == "Lotus"]
lotus_cars.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [43]:
# Select only columns "Engine HP", "Engine Cylinders".
lotus_cars = lotus_cars[["Engine HP", "Engine Cylinders"]]

In [44]:
lotus_cars = lotus_cars[["Engine HP", "Engine Cylinders"]].drop_duplicates()
lotus_cars.shape

(9, 2)

In [51]:
# Get the underlying NumPy array
X = np.array(lotus_cars)
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [52]:
# Transpose of Matrix X
X_T = X.T
X_T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [61]:
# Matrix-matrix multiplication between the transpose of X and X
XTX = X_T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [62]:
# Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [64]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

# Inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [65]:
# Multiply the inverse of XTX with the transpose of X

XTX_X_T = XTX_inv.dot(X_T)
XTX_X_T

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [66]:
# Multiply XTX_X_T by y
w = XTX_X_T.dot(y)
w

array([  4.59494481, -63.56432501])

In [70]:
# What's the value of the first element of w?
print("Value of first element of w is: ",  w[0])

Value of first element of w is:  4.594944810094579
